name: Push-to-KB

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            pandoc/latex # "ubuntu" is a more generic container
            # using "pandoc/latex" because of dependencies
            # used in the specific "build.sh"
        steps:
            - uses: actions/checkout@v2
            - name: Pushes to another repository
              uses: cpina/github-action-push-to-another-repository@main
              env:
                  SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
              with:
                  source-directory: "content"
                  destination-github-username: "FalixNodes-Software"
                  destination-repository-name: "Knowledge-base"
                  target-branch: main
                  commit-message: $ORIGIN_REPOSITORY_URL@commit
                  target-directory: "content"
